#!/usr/bin/env python3
"""Emit the structural schema of a log as TikZ.

Nodes are object types, arrows are the total functions the log carries. An
arrow drawn as a plain qualifier is recorded in that direction; one drawn with
an overbar is the inverse of a recorded relation, which is where most of the
schema actually lives and is the thing a reader will otherwise get backwards.
Parallel qualifiers between one pair are stacked on the arrow, because a pair
carrying several of them is what forces finite unions of maps rather than a
single map per pair.

Node area is scaled by the number of objects of the type, so the figure also
says which types are large; the source of the schema being the largest type is
not a coincidence and the picture should show it.

Generated rather than drawn. Usage:
    make_schema_graph.py <log.xml> [--layout=name:x,y ...] > schema.tex
"""

from __future__ import annotations

import sys
from collections import defaultdict

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from verify_handoff_export import parse  # noqa: E402

# Defined in paper/main.tex; hex lives there so the text, both generated
# figures and the drawn OCPN share one palette.
COLOR = {
    "items": "otItems",
    "employees": "otEmployees",
    "orders": "otOrders",
    "packages": "otPackages",
    "products": "otProducts",
    "customers": "otCustomers",
}

# Hand-placed, because a spring layout on six nodes reads worse than a drawn
# one and the shape carries meaning: sources left, sinks right.
LAYOUT = {
    "items": (0.0, 0.0),
    # Left of `items`, not under it: a vertical edge here runs straight through
    # the object-count label.
    "products": (-1.05, -1.25),
    "orders": (2.25, 0.80),
    "packages": (2.25, -0.80),
    "customers": (4.60, 0.80),
    "employees": (4.60, -0.80),
}

BEND = {
    ("items", "orders"): 8,
    ("items", "packages"): -8,
    ("orders", "customers"): 0,
    ("packages", "employees"): 0,
    ("customers", "employees"): 0,
    ("items", "products"): 0,
}


def total_maps(log):
    """(source, target) -> list of qualifiers, for total functions only."""
    fwd = defaultdict(lambda: defaultdict(set))
    for a, b, q in log.o2o:
        ta, tb = log.obj_type.get(a), log.obj_type.get(b)
        if ta is None or tb is None:
            continue
        fwd[(ta, tb, q, False)][a].add(b)
        fwd[(tb, ta, q, True)][b].add(a)

    by_type = defaultdict(set)
    for oid, ot in log.obj_type.items():
        by_type[ot].add(oid)

    out = defaultdict(list)
    for (s, t, q, inv), images in fwd.items():
        if len(images) != len(by_type[s]):
            continue
        if any(len(v) != 1 for v in images.values()):
            continue
        out[(s, t)].append((q, inv))
    return out, by_type


def main() -> None:
    log = parse(sys.argv[1])
    maps, by_type = total_maps(log)

    print("%% generated by code/make_schema_graph.py -- do not edit")
    print(rf"%% {len(maps)} total maps over {len(by_type)} object types")
    print(r"\begin{tikzpicture}[")
    print(r"    font=\scriptsize,")
    print(r"    ty/.style={draw, rounded corners=2pt, inner xsep=4pt,")
    print(r"               inner ysep=2.5pt, font=\scriptsize\ttfamily,")
    print(r"               fill=white, line width=0.6pt},")
    # Every arrow points the way the function runs. A dashed one says the log
    # records the relation the other way round. An open arrowhead was tried
    # first and is indistinguishable from a filled one at print size.
    print(r"    m/.style={-{Stealth[length=4pt,width=3.2pt]}, line width=0.7pt,")
    print(r"              black!70},")
    print(r"    mi/.style={m, dash pattern=on 2.2pt off 1.6pt},")
    print(r"    q/.style={font=\tiny\sffamily, black!60, inner sep=1.5pt,")
    print(r"              fill=white, rounded corners=1pt},")
    print(r"  ]")

    for t, (x, y) in LAYOUT.items():
        if t not in by_type:
            continue
        c = COLOR.get(t, "black")
        print(rf"  \node[ty, draw={c}!60, text={c}] ({t}) at ({x:.2f},{y:.2f}) "
              rf"{{{t}}};")
        n = f"{len(by_type[t]):,}".replace(",", r"{,}")
        # The count goes above when an edge leaves the node straight down,
        # because otherwise the arrow is drawn through the digits.
        down = any(
            {s2, t2} == {t, u}
            and abs(LAYOUT[u][0] - x) < 0.4
            and LAYOUT[u][1] < y
            for (s2, t2) in maps
            for u in (s2, t2)
            if u != t and u in LAYOUT
        )
        side = "above" if down else "below"
        print(rf"  \node[font=\tiny, black!45, {side}=0.5pt of {t}] {{{n}}};")

    for (s, t), quals in sorted(maps.items()):
        if s not in LAYOUT or t not in LAYOUT:
            continue
        # Beyond two, the stack is taller than the node it labels. The count is
        # what the reader needs anyway: a pair carrying several qualifiers is
        # what forces finite unions of maps rather than one map per pair.
        names = [q for q, _ in sorted(quals)]
        label = (r" \\ ".join(names) if len(names) <= 2
                 else rf"{names[0]} \\ +{len(names) - 1} more")
        # An edge gets the open tail head only when every qualifier on it is
        # read against the recorded direction; a pair carrying both would need
        # two edges and no log in the corpus has one.
        style = "mi" if all(inv for _, inv in quals) else "m"
        bend = BEND.get((s, t), 0)
        opt = f", bend left={bend}" if bend else ""
        print(rf"  \draw[{style}{opt}] ({s}) to "
              rf"node[q, align=center, midway] {{{label}}} ({t});")

    print(r"\end{tikzpicture}")


if __name__ == "__main__":
    main()
